Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Rails/FilePath:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'spec/*'
    - 'config/puma.rb'
